name: memos-dev

services:
  memos:
    container_name: memos-api-docker
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app/src
      - HF_ENDPOINT=https://hf-mirror.com
      - NEO4J_URI=bolt://neo4j-docker:7687
      # PostgreSQL + pgvector
      - VECTOR_DB_BACKEND=${VECTOR_DB_BACKEND:-pgvector}
      - POSTGRES_HOST=postgres18v
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-memos}
      - POSTGRES_DATABASE=${POSTGRES_DB:-memos}
      - POSTGRES_USER=${POSTGRES_USER:-memos}
      - POSTGRES_PASSWORD=${POST...CFm}
      # Authentication
      - AUTH_ENABLED=***
      - MASTER_KEY_HASH=8adbe28ceff5c38cd8f8a5b0c72ecc78076fb06b8de4d5f86b085c69ecc58fa1
    volumes:
      - ../src:/app/src
      - .:/app/docker
    networks:
      - 1panel-network

  neo4j:
    image: neo4j:5.26.6
    container_name: neo4j-docker
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: "neo4j/12345678"
    volumes:
      - /home/damxin/openclaw/workspace/memosdata/neo4j_data:/data
      - /home/damxin/openclaw/workspace/memosdata/neo4j_logs:/logs
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
